source: ./docs/
exclude: [_babel, src, ds4.browser.json, ds6.browser.json]
highlighter: rouge
url: https://ebay.github.io/skin
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cdn_path: https://ir.ebaystatic.com/cr/v/c1/skin
      version: 12.3.0-1
